#ifndef __LAB2_XMLTOKENTYPE_HPP__
#define __LAB2_XMLTOKENTYPE_HPP__

enum class XMLTokenType {

  XML_OPENING_TAG_WITH_ATTRIBUTES = 0,
  XML_OPENING_TAG_WITHOUT_ATTRIBUTES = 1,
  XML_OPENING_TAG_FINISH = 2,
  XML_CLOSING_TAG_WITH_ATTRIBUTES = 3,
  XML_CLOSING_TAG_WITHOUT_ATTRIBUTES = 4,
  XML_ATTRIBUTE_VALUE = 5,
  XML_EQUAL = 6,
  XML_TEXT = 7,
  XML_END = 8,
};

#endif
